[theme]

# Primary accent for interactive elements
primaryColor = '#E0E0E0'

# Background color for the main content area
backgroundColor = '#74512D'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor= '#543310'

# Color used for almost all text
textColor = '#FBF8F1'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"

